### ISSUE TITLE
gmRI package: Utility functions for GMRI RES Team

### ISSUE THREAD

**Issue by aallyn** [gulfofmaine/gmRi#35]

**Comment by aallyn** [comment]
High level issue tracker here. Below specific objectives for the gmRi package...

- [ ] Here's an objective, which might have a related issue, with the issues getting into specific tasks 
- [ ] Here's another

**Comment by abkfenris** [comment]
You might want to edit top level issue with what you currently have in the content. Otherwise the tasks aren't tracked.
