### ISSUE TITLE
Testing -- tasks related to objective 1

### ISSUE THREAD

**Issue by aallyn** [gulfofmaine/gmRi#36]
Example list of tasks needed to complete objective 1 -- I can't seem to assign these to a project though?
- [ ] Task1
- [x] Task2
- [ ] Task3

**Comment by abkfenris** [comment]
You can't assign a single checkbox task to a project, but you can turn them into issues, and each issue can be part of the project.

**Comment by adamkemberling** [comment]
Is there any reason to consider more than one project per repo? Or is it typical and easier to keep it at 1?

**Comment by aallyn** [comment]
I had been kind of thinking of it as a one to one, but I've got no clue if that's the best way to think about it...

**Comment by abkfenris** [comment]
I could see using more than one project per repo for focused work. Say if you do a hack week or some other fast paced development, you may want to stand up a short term project to track just that subset of work (without the overhead of filters).
